_BASE_: "Base-Pretrain.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  BATEXT:
    RECOGNIZER: "attn" 
SOLVER:
  IMS_PER_BATCH: 1
  # changed from 0.01
  BASE_LR: 0.0001
  STEPS: (160000, 220000)
  MAX_ITER: 260000
  # changed from 20000
  CHECKPOINT_PERIOD: 500
TEST:
  EVAL_PERIOD: 2
OUTPUT_DIR: "output/batext/pretrain/attn_R_50"